// [DEV FIXTURE] — replace with window.HoneyDB calls before production
import type { WorkTask } from './types'

export const MOCK_TASKS: WorkTask[] = [
  {
    id: 'task-1',
    title: 'A-05内検',
    colonyId: 'A-05',
    colonyName: 'A-05',
    apiaryName: '第1養蜂場',
    dueDate: '2026-09-07',
    status: 'overdue',
    priority: 'high',
    category: '内検',
  },
  {
    id: 'task-2',
    title: 'A-03高温確認',
    colonyId: 'A-03',
    colonyName: 'A-03',
    apiaryName: '第1養蜂場',
    dueDate: '2026-09-14',
    status: 'today',
    priority: 'medium',
    category: '環境確認',
  },
  {
    id: 'task-3',
    title: 'B-01給餌',
    colonyId: 'B-01',
    colonyName: 'B-01',
    apiaryName: '第2養蜂場',
    dueDate: '2026-09-14',
    status: 'today',
    priority: 'low',
    category: '給餌',
  },
  {
    id: 'task-4',
    title: 'A-02分蜂兆候確認',
    colonyId: 'A-02',
    colonyName: 'A-02',
    apiaryName: '第1養蜂場',
    dueDate: '2026-09-15',
    status: 'tomorrow',
    priority: 'medium',
    category: '内検',
  },
  {
    id: 'task-5',
    title: '器具を消毒',
    colonyId: undefined,
    colonyName: undefined,
    apiaryName: '全養蜂場',
    dueDate: '2026-09-17',
    status: 'upcoming',
    priority: 'low',
    category: 'メンテナンス',
  },
  {
    id: 'task-6',
    title: 'A-01採蜜',
    colonyId: 'A-01',
    colonyName: 'A-01',
    apiaryName: '第1養蜂場',
    dueDate: '2026-09-10',
    status: 'completed',
    priority: 'high',
    category: '採蜜',
    completedAt: '2026-09-10',
  },
  {
    id: 'task-7',
    title: 'B-02給餌',
    colonyId: 'B-02',
    colonyName: 'B-02',
    apiaryName: '第2養蜂場',
    dueDate: '2026-09-11',
    status: 'completed',
    priority: 'low',
    category: '給餌',
    completedAt: '2026-09-11',
  },
]
